spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8081

logging:
  level:
    root: INFO
    com.remizov: DEBUG

calculator:
  url: http://localhost:8080